# Generated by Django 2.2.7 on 2019-11-13 13:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('desc', models.TextField()),
                ('play_date_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_num', models.CharField(max_length=3)),
                ('movie', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='api.Movie')),
            ],
            options={
                'verbose_name_plural': 'Seats',
                'ordering': ('seat_num',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('seat', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.Seat')),
            ],
            options={
                'verbose_name_plural': 'Orders',
                'ordering': ('created_at',),
            },
        ),
    ]
