# Generated by Django 2.2.7 on 2019-11-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191113_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seat',
        ),
        migrations.AddField(
            model_name='order',
            name='seat',
            field=models.ManyToManyField(related_name='Seats', to='api.Seat'),
        ),
        migrations.RemoveField(
            model_name='seat',
            name='movie',
        ),
        migrations.AddField(
            model_name='seat',
            name='movie',
            field=models.ManyToManyField(related_name='Movies', to='api.Movie'),
        ),
    ]
