# Generated by Django 2.2.7 on 2019-11-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='title',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='content',
            new_name='pesan',
        ),
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.EmailField(default='no-email@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='ticket',
            name='nomor_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='nomor_telepon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='nomor_tiket',
            field=models.IntegerField(default=0),
        ),
    ]
