# Generated by Django 2.2.7 on 2019-11-12 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191112_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='nomor_order',
            new_name='harga',
        ),
    ]
