# Generated by Django 2.2.7 on 2019-11-13 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191113_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seat',
        ),
        migrations.AddField(
            model_name='order',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.Seat'),
        ),
        migrations.RemoveField(
            model_name='seat',
            name='movie',
        ),
        migrations.AddField(
            model_name='seat',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='api.Movie'),
        ),
    ]
