# Generated by Django 2.2.5 on 2019-11-12 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191112_0846'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='deskripsi',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='nama',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='waktu_tayang',
            new_name='play_date_time',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='film_id',
            new_name='movie_id',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='kursi_id',
            new_name='seat_num',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='order',
            name='nomor_telepon',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='harga',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='ketersediaan',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='tipe',
        ),
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 12, 11, 2, 13, 167943)),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 12, 11, 2, 13, 168822)),
        ),
        migrations.AddField(
            model_name='order',
            name='seat_id',
            field=models.SmallIntegerField(default=0),
        ),
    ]
